name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.1.app

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      # - name: Run a one-line script
      #   run: echo Hello, world!
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      - name: Install Package for mint
        run: brew install mint
