name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.1.app

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      # - name: Run a one-line script
      #   run: echo Hello, world!
      - name: Install Plugin for rbenv
        run: |
          rubyVersionBinaryPath="$(rbenv root)""/versions/""$(< .ruby-version)""/bin/ruby"
          if [ -e "$rubyVersionBinaryPath" ]; then
              :
          else
              brew update && brew upgrade ruby-build || true
              rbenv install "$(< .ruby-version)"
          fi
      - name: Install Package for mint
        run: brew install mint

